### ISSUE TITLE
ui: nits: 'Dns log settings > Add IP' certain icon colors don't show up 

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#261]
The below 'roku' icon is configured as orange in the 'devices' view but for some reason the color doesn't seem to carry out to this UI
<img width="293" alt="iconcolor" src="https://github.com/spr-networks/super/assets/1476421/c549c816-3724-4193-a659-92b4dc58a8c0">

**Comment by 0vercl0k** [comment]
It's actually not iOS specific; on the website version, the same behavior can be soon on the 'System>groups'  view
<img width="260" alt="image" src="https://github.com/spr-networks/super/assets/1476421/3009d9b8-5803-4805-8bba-8e4a2f70ba17">

**Comment by lts-rad** [comment]
maybe @lts-po knows off hand how the colors work in this menu

**Comment by lts-po** [comment]
> It's actually not iOS specific; on the website version, the same behavior can be soon on the 'System>groups' view.

Should be fixed now in dev. orange got nuked when ported to gluestack. Will be avail in next release

**Comment by 0vercl0k** [comment]
I think this bug still exist at least on the web ui; the new traffics widget on the main page don't pull the orange color either - should I open a new bug?

**Comment by lts-rad** [comment]
gluestack vs orange:

![image](https://github.com/spr-networks/super/assets/37549748/b20acb43-d041-4704-9ddb-d7f7a52e8d55)

**Comment by lts-rad** [comment]
we have not reproduced this yet

**Comment by 0vercl0k** [comment]
How can I help? Sorry somehow I missed this - it happens all the time for
me.

Cheers

**Comment by lts-rad** [comment]
All good. we are baffled on how to reproduce at the moment :-). but it sounds like there is a way

**Comment by 0vercl0k** [comment]
Haha, can it be something that repro on mine because of an old
configuration or something?

Cheers

**Comment by lts-po** [comment]
Yes could be old config from when we changed the color scheme.
It should work to set the color again to update the device if its still buggy

**Comment by 0vercl0k** [comment]
I've tried to update the device set another color + set this back to orange and it'll still be displayed as blue in the UIs. Am I doing anything wrong? 😅
