### ISSUE TITLE
ios: DNS overide, hard to tell when deleting an entry

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#306]
On the iOS app, when trying to delete a DNS override entry, it is pretty hard to click on the red ❌ button as it is small; and somehow you also don't get any feedback when a click has been dispatched. That plus a small lag lead to clicking several times in a row and deleting multiple entries.

I can probably try to make a video if that's useful, but it wouldn't even be visible when I am tapping on the screen so not sure it'd be super useful.

Cheers

**Comment by 0vercl0k** [comment]
I also noticed that this control is also used in the DNS logging settings UI and it has the same effect; you never know when you properly the ❌ and sometime end up deleting two entries when you wanted to delete one

**Comment by lts-po** [comment]
Pushed a new version to TestFlight with a swipelist similar to device listing - check if this is better. Plan is if it works, we move more of the listings to this layout for iOS (blocklists, rules, groups, any listing) & add more buttons to the hidden view.

Thanks again!
![block-swipe](https://github.com/spr-networks/super/assets/37542945/5bde42b2-871b-4411-9e28-10d130a828b2)

**Comment by 0vercl0k** [comment]
Woot this is looking great!

**Comment by 0vercl0k** [comment]
The 'Dns Log Settings' / 'Host Privacy IP List' seems to have the old little red ❌; not sure if it was missed or it regressed somehow?

**Comment by lts-rad** [comment]
looking into it now, this view disappeared from routes and wasnt rendering properly on web. as for whyios is not picking up the swipelist im not sure. i dont actually see a code change for settings for using DNSOverrideListItem which got the swipe list in  https://github.com/spr-networks/super/commit/340b5dff03266bc09b7944af11eb799893fcf8d0

**Comment by lts-rad** [comment]
xcrun is currently failing for the PR. https://github.com/spr-networks/super/actions/runs/9026717967/job/24804460927 . its possible testflight is grabbing the wrong version

**Comment by lts-rad** [comment]
the dns override at least has it, so im thinking maybe it didnt make it to the log settings previously

**Comment by lts-rad** [comment]
is this resolved now? as of v0.3.14

**Comment by 0vercl0k** [comment]
This is fixed in the DNS override view yes, but it isn't fixed in the 'DNS Log > Log Settings > Host Privacy IP List' view.

Cheers

**Comment by 0vercl0k** [comment]
Bumping this as this is still an issue on latest v1.0.4!

Cheers
